### ISSUE TITLE
sourcemap didn't effective

### ISSUE THREAD

**Issue by ambershi1** [grafana/faro-javascript-bundler-plugins#16]
I successfully uploaded the sourcemap and I can see the sourcemap list showed on the grafana front-end, but the error detail didn't convert stack traces from JavaScript browser errors back into their original representation after I upload the sourcemap

the error show below, it turns out whether I upload the sourcemap or not, it shows the same error detail, how does the sourcemap associate with our js file? is there any possible problem about the usage or do I missing anything?
Error: test sourcemap
  at onClick (http://127.0.0.1:8080/xxx.js:537:2618)
  at Object.lj (https://cdn.jsdelivr.net/npm/react-dom@18.2.0/umd/react-dom.production.min.js:223:217)
  at  (:0:0)
  at  (:0:0)
  at  (:0:0)
  at  (:0:0)
  at  (:0:0)
  at  (:0:0)
  at  (:0:0)
  at  (:0:0)
  
  the integration works that I do:
  //add in webpack
  new FaroSourceMapUploaderPlugin({
        appName: 'Welcome',
        endpoint: 'xxx',
        appId: 'xxx',
        stackId: 'xxx',
        apiKey: webpackConfigEnv.FaroSourceMapKey,
        gzipContents: true
      })
    ]
  
  
  look forward to your response!!

**Comment by eskirk** [comment]
hi @ambershi1 sorry for the delay 

are you still experiencing this issue? if so, please provide me with some more details so I can better identify what the problem is.

can you share: 
- your configuration of the Faro web SDK? specifically the `initializeFaro` portion
- the rest of the configuration of your webpack configuration 
- the output of your bundler when you run it

let me know - thank you

**Comment by ambershi1** [comment]
I'm afraid I just can provide the below info, and also I pick one sourcemapId: 17223298533471066c174d4 which was shown in Source Map List, does that useful?
```
plugins: [
  // other plugins...
  new FaroSourceMapUploaderPlugin({
    appName: 'Harness',
    endpoint: 'https://faro-api-prod-us-central-0.grafana.net/faro/api/v1',
    appId: '1117',
    stackId: '399567',
    apiKey: 'api-key',
    gzipContents: true,
  }),
],
```
@eskirk

**Comment by eskirk** [comment]
@ambershi1 in order to be able diagnose this issue I will need to know how you initialize the Faro web SDK.

**Comment by boris-jarkowicz** [comment]
@eskirk Hey there,

i am not OP, but i am experiencing a similar issue where the upload seems to work in terms of logging at the verbose log output, it finishes with an output of uploaded sourcemaps. The config looks identical to the one @ambershi1 did post and then you asked for how the initialization of the Faro Web SDK looks like. I wanted to provide our configuration to maybe to work towards a solution of this issue.

```
import type { BrowserConfig } from '@grafana/faro-web-sdk';
import { getWebInstrumentations, initializeFaro } from '@grafana/faro-web-sdk';

  const faroConfig: BrowserConfig = {
    url: collectorUrl,
    trackWebVitalsAttribution: true,
    instrumentations: [
      ...getWebInstrumentations(), // Web instrumentations for error reporting
    ],
    app: {
      name,
      version,
      environment,
    },
    sessionTracking: {
      samplingRate: Math.min(sampleRate ?? maxSampleRate, maxSampleRate),
    },
    beforeSend,
  };

  try {
    initializeFaro(faroConfig);
  } catch (error) {
    // Handle any errors that occur during initialization
    console.error('Error initializing Faro:', error);
  }
``` 

and in the webpack prod config:

```
new FaroSourceMapUploaderPlugin({
    verbose: true,
    appName: 'our-app',
    endpoint: 'collector-prod-v1-url',
    appId: 'appId',
    stackId: 'stackId',
    apiKey: 'apiKey',
    gzipContents: true,
    outputPath: path.resolve(paths.root, `build/our-product/static`),
}),
```

Using this configuration we have no working sourcemaps unfortunately and in the Faro UI no new sourcemap entries are arriving, meaning the "Settings --> Source Maps" view is never updating with any entries although the log output states the uploading was successful. We also made an attempt using cURL and the upload also succeeded with `201 Created`, to no avail though.

Anyone know something? :)

**Comment by eskirk** [comment]
hey @boris-jarkowicz thanks for sharing - is the name that you use for `app.name` in the `initializeFaro` config the same as the name in the `appName` of the uploader plugin?

**Comment by boris-jarkowicz** [comment]
> hey [@boris-jarkowicz](https://github.com/boris-jarkowicz) thanks for sharing - is the name that you use for `app.name` in the `initializeFaro` config the same as the name in the `appName` of the uploader plugin?

Yes it is identical.

**Comment by abuecker** [comment]
@eskirk I'm experiencing a similar issue.  I'm unable to upload via the Vite plugin.  When trying to upload via `curl`, the upload succeeds but then gets a `Missing role in request` in the body of the response:

```bash
$ curl -X POST \
      -H "Content-Type: application/json" \
      -H "Authorization: Bearer 1126586:***" \
      -d @dist/assets/index-CjtCu4DW.js.map \
      https://faro-api-prod-us-west-0.grafana.net/faro/api/v1/app/902/sourcemaps/CjtCu4DW -v

...
< HTTP/1.1 100 Continue
* We are completely uploaded and fine
< HTTP/1.1 401 Unauthorized
< Content-Length: 24
< Content-Type: text/plain; charset=utf-8
< Date: Thu, 23 Jan 2025 01:53:27 GMT
< X-Content-Type-Options: nosniff
<
Missing role in request
```

Following [this documentation](https://grafana.com/docs/grafana-cloud/monitor-applications/frontend-observability/sourcemap-uploads/sourcemap-upload-curl/).

**Comment by boris-jarkowicz** [comment]
Any more inputs on this? :) @eskirk

**Comment by mteimoori** [comment]
The 401 error `Missing role in request` is new and has been happening since yesterday.

**Comment by eskirk** [comment]
@boris-jarkowicz interesting... so your source maps are never showing up in the UI, correct? if you could email me at my work email `elliot.kirk@grafana.com` I can better debug this issue without sharing any of your instance details on this public forum. let me know if thats ok with you.

**Comment by eskirk** [comment]
as for the new 401 issues, we changed some RBAC permissions in our backend and it looks like the source map uploads were an unintended casualty. I will debug and try to resolve that issue today. stay tuned and thanks for the reports.

**Comment by eskirk** [comment]
I will close this for now since we have rolled out some fixes - feel free to tag me and I will re-open if this issue persists.

**Comment by errorproofdev** [comment]
@eskirk - currently experiencing the 401 errors utilizing `@grafana/faro-webpack-plugin` on a NextJS App Router @ v14.2.30.

Using an access token with sourcemaps:* (read, write, delete).

Example Error:

`[Faro] Uploading 6231-dc888d9bb72c3938.js.map to https://faro-api-prod-us-west-0.grafana.net/faro/api/v1/app/[redacted]/sourcemaps/[redacted]
   Linting and checking validity of types  .[Faro] Upload of 6231-dc888d9bb72c3938.js.map failed with status: 401`

Any ideas what I'm missing here? I've never been able to get this working, however, this is the closest I've gotten after specifying `output-path`.

```
new FaroSourceMapUploaderPlugin({
          appName: process.env.NEXT_PUBLIC_FARO_APP_NAME,
          endpoint: 'https://faro-api-prod-us-west-0.grafana.net/faro/api/v1',
          appId: process.env.GRAFANA_CLOUD_APP_ID,
          stackId: process.env.GRAFANA_CLOUD_STACK_ID,
          apiKey: process.env.GRAFANA_SOURCE_MAPS_API_KEY,
          outputPath: path.resolve(`.next/static/chunks`), //this is potentially where the issue lies... if I don't include this prop it doesn't upload anything
          verbose: true,
        }),
```

**Comment by bferreira** [comment]
We are having the same issue, where our sourcemaps don't show.
We are using it with NextJS:
'@grafana/faro-web-tracing': 1.19.0
  '@grafana/faro-web-sdk': 1.19.0
  '@grafana/faro-webpack-plugin': 0.6.0
Is there something I should check from the Grafana side if the fixes are there?

**Comment by eskirk** [comment]
@bferreira can you share details about your source map issues? are they not uploading to Grafana cloud? are you getting errors during the upload? are they uploading but not de-obfuscating your source maps?

**Comment by sinchang** [comment]
@eskirk  

I met the same issue on my project https://github.com/XChangLab/faro-demo. I saw the soucemaps uploaded successfully on the terminal.

<img width="2998" height="872" alt="Image" src="https://github.com/user-attachments/assets/ad239377-1e12-45f9-9e60-fcb30d998119" />

But did not see the error source code location in the error stacktrace

<img width="1850" height="1080" alt="Image" src="https://github.com/user-attachments/assets/34a7f2ec-0c9b-4c53-940b-09954debc093" />

**Comment by bferreira** [comment]
As [sinchang](https://github.com/sinchang) describes.

I find the source map on the list. No errors while uploading:

<img width="1576" height="273" alt="Image" src="https://github.com/user-attachments/assets/036a04e7-f87d-4d46-96fb-c2869a09ca1e" />

The error:
<img width="1527" height="734" alt="Image" src="https://github.com/user-attachments/assets/2c2ab7a7-6228-4e77-bb20-88cd207d0600" />

It is our CI step that pushes the files to Grafana:
```
          npx -y @grafana/faro-cli upload \
            --endpoint 'https://${{ inputs.GRAFANA_FARO_HOST }}/faro/api/v1' \
            --app-name '${{ inputs.app-name }}' \
            --app-id '${{ inputs.grafana-faro-app-id }}' \
            --api-key "${{ secrets.GRAFANA_FARO_API_KEY }}" \
            --stack-id '538357' \
            --bundle-id "${{ steps.bundle-id.outputs.bundle_id }}" \
            --output-path "./sourcemaps" \
            --verbose
```

Anything on the source-maps that I should check for to see if they are correct?

**Comment by sinchang** [comment]
@eskirk How to support NextJS files that upload to the CDN in plugin version 0.7.0?

**Comment by harshagarwal08-2** [comment]
Hey I am facing a similar issue right now.
I am using nextjs turbo which creates source maps in the .next folder and I am able to upload those source maps using the faro-cli. But the errors I see are still using the bundled stack trace and not the source map. Can someone help?
