### ISSUE TITLE
Missing Angular Documentation

### ISSUE THREAD

**Issue by willcooley** [grafana/faro-javascript-bundler-plugins#19]
Is there an example on how to use Grafana Faro sourcemaps with an Angular code base with the new builders? The current documented Grafana support is in regards to rollup/ ViteJs and Webpack; which would be the older build system, or custom build setup. Angular uses EsBuild for compiler, and ViteJs only for local dev  server; so there seems to be a gap without having to modify one's build system configuration for just sourcemaps to be registered in the app. 

In addition, Angular compiles its own sourcemaps; so is there a way of adapting current Angular sourcemaps by prepending file references in the bundles where they can be used?

**Comment by eskirk** [comment]
@willcooley sorry for the delayed response, lets see if we can get this resolved. 

I am pretty unfamiliar with Angular these days, but if I am understanding you correctly it sounds like the main ask here is an EsBuild bundler plugin, right? 

if thats the case that is a relatively easy ask and something I can try to prioritize in the near future.

**Comment by ALPNP** [comment]
Hi all.

My stack:
Angular 18.2.0 with SSR.
@grafana/faro-web-sdk 1.12.3
@grafana/faro-web-tracing 1.13.1

My production build pipeline uses esbuild, faro sdk initialized only in browser.
I adde flag for source-maps generation in angular cli, but if i upload source-maps into grafana-cloud by curl, my error stacktraces looks like:

- Grafana cloud error stacktrace:
Error: console.error: BigBug
  at e.openSidenav (http://localhost:4000/super-assets/main-JY32AW4P.js:2:40250)
  at ? (http://localhost:4000/super-assets/main-JY32AW4P.js:2:39500)
  at E_ (http://localhost:4000/super-assets/chunk-5Z6PU5VY.js:7:104543)
  at o (http://localhost:4000/super-assets/chunk-5Z6PU5VY.js:7:104729)
  at HTMLElement.<anonymous> (http://localhost:4000/super-assets/chunk-5Z6PU5VY.js:8:27651)
  at f.invokeTask (http://localhost:4000/super-assets/polyfills-Q763KACN.js:1:7068)
  at Object.onInvokeTask (http://localhost:4000/super-assets/chunk-5Z6PU5VY.js:7:29654)
  at f.invokeTask (http://localhost:4000/super-assets/polyfills-Q763KACN.js:1:6989)
  at t.runTask (http://localhost:4000/super-assets/polyfills-Q763KACN.js:1:2375)
  at E.invokeTask [as invoke] (http://localhost:4000/super-assets/polyfills-Q763KACN.js:1:8144)

- Browser error stacktrace:
Error: BigBug
    at e.openSidenav (header.component.ts:99:11)
    at header.component.html:109:51
    at E_ (core.mjs:25831:12)
    at o (core.mjs:25863:18)
    at HTMLElement.<anonymous> (platform-browser.mjs:679:112)
    at f.invokeTask (polyfills-Q763KACN.js:1:7068)
    at Object.onInvokeTask (core.mjs:7046:25)
    at f.invokeTask (polyfills-Q763KACN.js:1:6989)
    at t.runTask (polyfills-Q763KACN.js:1:2375)
    at E.invokeTask [as invoke] (polyfills-Q763KACN.js:1:8144)

@eskirk Eah, we have problems, because we don't have plugin @grafana/faro-esbuild-plugin, only for Webpack and Rollup.
https://grafana.com/docs/grafana-cloud/monitor-applications/frontend-observability/sourcemap-uploads/

**Comment by ALPNP** [comment]
@willcooley Maybe you fix that ?

**Comment by nicolaric** [comment]
any updates on that? 😁

**Comment by willcooley** [comment]
@eskirk basically there needs to be a post build script that can be run via CLI that can modify  and upload the sourcemaps to Grafana. Sentry does this currently, and it works very well. Due to the fact of not knowing the exact schema that is required for Sourcemap upload and association to errors, I'm not going to be able to help. The current solutions offered are integrated during the compilation process, but Angular doesn't expose this to be hooked into; so it has to be a post process script.

**Comment by eskirk** [comment]
@willcooley all very good points. I just finished up the first version of the Faro sourcemap CLI tool and I think I could make some additions to add a "prepend bundle ID" functionality that should accomplish exactly this. 

let me think about this and see when I can get this taken care of. would like to have angular support this quarter...

**Comment by nicolaric** [comment]
@eskirk you know that this quarter ends in 12 days, right? 😝

**Comment by eskirk** [comment]
@nicolaric at least getting it started this quarter :)
